FROM maven AS build
WORKDIR /verifica
COPY src /verifica/src
COPY pom.xml /verifica
RUN mvn -f /verifica/pom.xml clean package -DskipTests

FROM openjdk:11-jre-slim
COPY --from=build /verifica/target/Testar-1.0-SNAPSHOT.jar /usr/local/lib/Testar.jar
ENTRYPOINT ["java", "-jar", "/usr/local/lib/Testar.jar"]